Add compatibility with PHPUnit 9.3
guzzle/promises pull request #118
Opened 2020-09-12 14:21 UTC by villfa

This is a required step to build the project with PHP8.

2020-09-12 21:35 UTC, GrahamCampbell commented
Will conflict with https://github.com/guzzle/promises/pull/113.

2020-09-13 12:39 UTC, villfa commented
@GrahamCampbell I have reworked the PR hoping this will make the merge easier

2020-09-19 09:15 UTC, Nyholm commented
Could you please rebase this PR?

2020-09-19 11:43 UTC, Nyholm commented
I started working on PHP8 another ago. I see that that PR is using PHPUnit 9.3.10 with the symfony phpunit bridge. 

Have a look at #122. What are the pros/cons between that approach?

2020-09-19 11:47 UTC, Nyholm requested changes

2020-09-19 11:47 UTC, Nyholm commented on tests/FulfilledPromiseTest.php
> +namespace GuzzleHttp\Promise\Tests;
Good catch!

2020-09-19 11:47 UTC, Nyholm commented on tests/TestCase.php
> +    public function setExpectedException($exception, $message = null, $code = null)
This is actually the job of Symfony PHPUnit bridge.

2020-09-19 11:47 UTC, Nyholm commented on tests/UtilsTest.php
> +        $this->assertTrue(strpos($result->getMessage(), 'foo') !== false, "'" . $result->getMessage() . " does not contain 'foo'");
assertStringContainsString

2020-09-19 11:49 UTC, villfa commented
> I started working on PHP8 another ago. I see that that PR is using PHPUnit 9.3.10 with the symfony phpunit bridge.
> 
> Have a look at #122. What are the pros/cons between that approach?

When I have originally open this PR I wanted to keep it as minimal as possible.
Now that *phpunit-bridge* has been added I think it's not relevant to maintain this PR anymore.
I'm closing it in favor of yours.

2020-09-19 11:49 UTC, closed without merging

2020-09-19 11:52 UTC, Nyholm commented
Yeah, I appreciate that. 

This morning when I started with this library I had no plans of creating PHP8 support. 

Thank you for you work.